application: ulmaceaetree
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /tree\.ico
  static_files: tree.ico
  upload: tree\.ico

- url: /images
  static_dir: images

- url: /stylesheets
  static_dir: stylesheets
- url: /js
  static_dir: js
- url: /
  script: main.app
  login: optional

- url: .*
  script: main.app
  login: required

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
